services:
  - type: web
    name: canada-house-price-backend
    env: python
    region: ohio
    plan: free
    rootDirectory: backend
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
   
